[application]

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Voyage"

[web.watcher]

index_on_404 = true

watch_path = ["src"]

[bundle]
# Bundle identifier
identifier = "app.voyage.zachatrocity"

# Bundle publisher
publisher = "Zach Russell"

# Bundle icon
icon = ["assets/icons/icon-1024.png", "assets/icons/icon-512.png", "assets/icons/icon-192.png", "assets/icons/icon-144.png", "assets/icons/icon-96.png", "assets/icons/icon-72.png", "assets/icons/icon-48.png"]

# Bundle resources
resources = ["assets/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Travel"

# Bundle short description
short_description = "A self-hosted travel email aggregator."

# Bundle long description
long_description = """
Voyage searches your inbox for travel confirmations, itineraries, and bookings.
"""
