#!/usr/bin/env python3
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SWAGGER = ROOT.parent / "voyage-backend" / "docs" / "swagger.json"
OUT = ROOT / "src" / "generated" / "api_types.rs"

NAME_OVERRIDES = {
    "notmuch.EmailResult": "EmailResult",
    "handlers.tripResponse": "TripResponse",
    "handlers.tripsResponse": "TripsResponse",
    "handlers.TripEmailItem": "TripEmailItem",
    "handlers.tripEmailsResponse": "TripEmailsResponse",
    "handlers.associateTripEmailResponse": "AssociateTripResponse",
    "handlers.createTripRequest": "CreateTripBody",
    "handlers.searchResponse": "SearchResults",
}


def pascal_case(text: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", text)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if out and out[0].isdigit():
        out = f"T{out}"
    return out or "GeneratedType"


def rust_type(prop: dict, defs: dict) -> str:
    if "$ref" in prop:
        ref = prop["$ref"].split("/")[-1]
        return rust_name(ref)

    t = prop.get("type")
    fmt = prop.get("format")

    if t == "string":
        return "String"
    if t == "integer":
        return "i64" if fmt != "int32" else "i32"
    if t == "number":
        return "f64"
    if t == "boolean":
        return "bool"
    if t == "array":
        inner = rust_type(prop.get("items", {}), defs)
        return f"Vec<{inner}>"
    if t == "object":
        additional = prop.get("additionalProperties")
        if additional:
            v = rust_type(additional, defs)
            return f"std::collections::HashMap<String, {v}>"
        return "serde_json::Value"

    return "serde_json::Value"


def rust_name(def_name: str) -> str:
    if def_name in NAME_OVERRIDES:
        return NAME_OVERRIDES[def_name]

    # Keep last token as primary signal, but include namespace when needed.
    if "." in def_name:
        ns, tail = def_name.split(".", 1)
        return pascal_case(f"{ns}_{tail}")
    return pascal_case(def_name)


def field_name(name: str) -> str:
    n = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if re.match(r"^[0-9]", n):
        n = f"f_{n}"
    if n in {"type", "match", "ref", "self", "super", "crate"}:
        n = f"{n}_field"
    return n


def generate(swagger_path: Path) -> str:
    data = json.loads(swagger_path.read_text())
    defs = data.get("definitions", {})

    lines = []
    lines.append("// @generated by scripts/generate_api_types.py; DO NOT EDIT BY HAND.\n")
    lines.append("use serde::{Deserialize, Serialize};\n")

    for def_name in sorted(defs.keys()):
        schema = defs[def_name]
        if schema.get("type") != "object":
            continue

        struct_name = rust_name(def_name)
        props = schema.get("properties", {})
        required = set(schema.get("required", []))

        lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        lines.append(f"pub struct {struct_name} {{")

        for prop_name in sorted(props.keys()):
            prop = props[prop_name]
            fname = field_name(prop_name)
            ty = rust_type(prop, defs)
            if prop_name not in required:
                ty = f"Option<{ty}>"

            if fname != prop_name:
                lines.append(f"    #[serde(rename = \"{prop_name}\")]")
            lines.append(f"    pub {fname}: {ty},")

        if not props:
            lines.append("    #[serde(flatten)]")
            lines.append("    pub extra: serde_json::Value,")

        lines.append("}\n")

    return "\n".join(lines)


def main():
    swagger_path = DEFAULT_SWAGGER
    content = generate(swagger_path)
    OUT.write_text(content)
    print(f"Generated {OUT} from {swagger_path}")


if __name__ == "__main__":
    main()
